version: "3"

networks:
  internal:

volumes:
  storage-volume:

services:
  storage:
    container_name: postgres
    image: "postgres:13"
    environment:
      - POSTGRES_USER=manydecks
      - POSTGRES_PASSWORD=manydecks
    networks:
      - internal
    volumes:
      - storage-volume:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    container_name: server
    image: "massivedecks/manydecks-server:latest"
    #build: "./server"
    depends_on:
      - storage
    environment:
      - NODE_ENV=production
    networks:
      - internal
    restart: unless-stopped

  client:
    container_name: client
    image: "massivedecks/manydecks-client:latest"
    #build: "./client"
    depends_on:
      - server
    ports:
      - "80:8080"
      - "443:8083"
    networks:
      - internal
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
