#!/bin/bash

docker build \
    --build-arg VCS_REF="`git rev-parse HEAD`" \
    --build-arg BUILD_DATE="`date --rfc-3339=seconds`" \
    --build-arg VERSION="`git describe --tags`" \
    -t $IMAGE_NAME .
